In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive

In [ ]:
from tensorflow.keras.models import Sequential,Model,load_model
from tensorflow.keras.layers import Dense,Flatten,Conv2D,MaxPooling2D,Dropout
from tensorflow.keras import utils,optimizers
import numpy as np
import cv2
from sklearn.utils import shuffle
import matplotlib.pyplot as plot
import os, math
from random import randint
import matplotlib.pyplot as plt
import tensorflow as tf
import random
import pandas as pd
import datetime
import os, shutil
from keras.preprocessing.image import ImageDataGenerator
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score ,confusion_matrix, auc, f1_score, precision_score, recall_score, roc_curve
from tensorflow import keras
from tensorflow.keras.utils import plot_model
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Dropout, Flatten, Dense, Activation, BatchNormalization

In [ ]:
a =["banana", "carrot", "corn" ,"dragonfruit", "garlic", "guava", "peanut", "pineapple", "pumpkin", "rice", "soybean", "sugarcane", "tomato", "bareland"]
all=pd.DataFrame()
for name in a:

  path = ('/content/gdrive/MyDrive/Colab Notebooks/Aidea/data/train/'+name)
  df_path =os.listdir(path)
  plants=pd.DataFrame({'pic_name':df_path})
  # if name == "banana":
  #   plants['label']= '0'
  # elif name == "carrot":
  #   plants['label']= '1'
  # elif name == "corn":
  #   plants['label']= '2'
  # elif name == "dragonfruit":  
  #   plants['label']= '3'
  # elif name ==  "garlic":
  #   plants['label']= '4'
  # elif name == "guava":
  #   plants['label']= '5'
  # elif name == "peanut":
  #   plants['label']= '6'
  # elif name == "pineapple":
  #   plants['label']= '7'
  # elif name == "pumpkin":
  #   plants['label']= '8'
  # elif name ==  "rice":
  #   plants['label']= '9'
  # elif name == "soybean":
  #   plants['label']= '10'
  # elif name == "sugarcane":
  #   plants['label']= '11'
  # elif name == "tomato":
  #   plants['label']= '12'
  # elif name == "bareland":
  #   plants['label']= '13'
  plants['label']= name
  plants['path']= name+'/'+plants['pic_name']


  # plants.loc[plants.pic_name]
  all=pd.concat([all,plants])
  # all=shuffle(all)
all

                pic_name     label                          path
0        banana_cut0.jpg    banana        banana/banana_cut0.jpg
1        banana_cut1.jpg    banana        banana/banana_cut1.jpg
2        banana_cut2.jpg    banana        banana/banana_cut2.jpg
3        banana_cut3.jpg    banana        banana/banana_cut3.jpg
4        banana_cut4.jpg    banana        banana/banana_cut4.jpg
..                   ...       ...                           ...
495  bareland_cut495.jpg  bareland  bareland/bareland_cut495.jpg
496  bareland_cut496.jpg  bareland  bareland/bareland_cut496.jpg
497  bareland_cut497.jpg  bareland  bareland/bareland_cut497.jpg
498  bareland_cut498.jpg  bareland  bareland/bareland_cut498.jpg
499  bareland_cut499.jpg  bareland  bareland/bareland_cut499.jpg

[7000 rows x 3 columns]

In [ ]:
from numpy.core.numeric import tensordot
earlystop = EarlyStopping(patience = 6)
lr_reduction= ReduceLROnPlateau( monitor='val_loss', 
                  factor=0.5, 
                  patience=2,
                  min_lr=0.00001)
# logdir = os.path.join('logs',datetime.datetime.now().strftime("%Y%m%d-%H%M%S"))
# tensorboard_callback=tf.keras.callbacks.TensorBoard(logdir, histogram_freq=1)
callbacks = [earlystop, lr_reduction]#,tensorboard_callback]

#MODEL

In [ ]:
inputs =keras.Input(shape=(224, 224, 3),name='Input')

con2D_h1=Conv2D(64,(3,3),activation='relu',name='con2D_h1')(inputs)
con2D_h2=Conv2D(64,(3,3),activation='relu',name='con2D_h2')(con2D_h1)
normzlization1 =BatchNormalization(name='normzlization1')(con2D_h2)
pooling1 =MaxPooling2D(pool_size=(2,2),name='pooling1')(normzlization1)

con2D_h3=Conv2D(128,(3,3),activation='relu',name='con2D_h3')(pooling1)
con2D_h4=Conv2D(128,(3,3),activation='relu',name='con2D_h4')(con2D_h3)
normzlization2 =BatchNormalization(name='normzlization2')(con2D_h4)
pooling2 =MaxPooling2D(pool_size=(2,2),name='pooling2')(normzlization2)

con2D_h5=Conv2D(256,(3,3),activation='relu',name='con2D_h5')(pooling2)
con2D_h6=Conv2D(256,(3,3),activation='relu',name='con2D_h6')(con2D_h5)
normzlization3 =BatchNormalization(name='normzlization3')(con2D_h6)
pooling3 =MaxPooling2D(pool_size=(2,2),name='pooling3')(normzlization3)

con2D_h7=Conv2D(512,(3,3),activation='relu',name='con2D_h7')(pooling3)
con2D_h8=Conv2D(512,(3,3),activation='relu',name='con2D_h8')(con2D_h7)
normzlization4 =BatchNormalization(name='normzlization4')(con2D_h8)
pooling4 =MaxPooling2D(pool_size=(2,2),name='pooling4')(normzlization4)

con2D_h9=Conv2D(512,(3,3),activation='relu',name='con2D_h9')(pooling4)
con2D_h10=Conv2D(512,(3,3),activation='relu',name='con2D_h10')(con2D_h9)
normzlization5 =BatchNormalization(name='normzlization5')(con2D_h10)
pooling5 =MaxPooling2D(pool_size=(2,2),name='pooling5')(normzlization5)

flatten =Flatten(name='flatten1')(pooling5)
dense1 =Dense(1024,activation='relu',name='dense1')(flatten)
normzlization7 =BatchNormalization(name='normzlization7')(dense1)
dense2 =Dense(1024,activation='relu',name='dense2')(normzlization7)
normzlization6 =BatchNormalization(name='normzlization6')(dense2)

output =Dense(14,activation='softmax',name='dense3')(normzlization6)

model=keras.Model(inputs=inputs,outputs=output)

opt = optimizers.Adam(learning_rate=0.0001)
model.compile(loss='categorical_crossentropy',metrics=['accuracy'],optimizer=opt)

In [ ]:
# train_df, test_df= train_test_split(all, test_size=0.15 ,random_state=0)
all=shuffle(all)
batch_size = 32
image_size = (224,224)
# total_train=train_df.shape[0]

In [ ]:
# print(train_df.shape)

In [ ]:
train_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=15,
    width_shift_range=0.1,
    height_shift_range=0.1,
    shear_range=0.1,
    zoom_range=0.2,
    horizontal_flip=True,
    validation_split=0.15 )

train_generator = train_datagen.flow_from_dataframe(
    all,
    '/content/gdrive/MyDrive/Colab Notebooks/Aidea/data/train/',
    x_col='path',
    y_col='label',
    target_size=image_size,
    class_mode='categorical',
    batch_size=batch_size,
    subset='training'
)

Found 5950 validated image filenames belonging to 14 classes.

In [ ]:
validation_generator = train_datagen.flow_from_dataframe(
    all,
    '/content/gdrive/MyDrive/Colab Notebooks/Aidea/data/train/',
    x_col='path',
    y_col='label',
    target_size=image_size,
    class_mode='categorical',
    batch_size=batch_size,
    subset='validation'
)

Found 1050 validated image filenames belonging to 14 classes.

In [ ]:
epochs=5
model.fit(
  train_generator,
  epochs=epochs,
  validation_data= validation_generator,
  # steps_per_epoch= total_train//batch_size,
  validation_steps = validation_generator.samples// batch_size,
  callbacks=callbacks
)

Epoch 1/5
186/186 [==============================] - 108s 580ms/step - loss: 0.1849 - accuracy: 0.9420 - val_loss: 0.5172 - val_accuracy: 0.8447 - lr: 1.2500e-05
Epoch 2/5
186/186 [==============================] - 108s 581ms/step - loss: 0.1766 - accuracy: 0.9445 - val_loss: 0.5531 - val_accuracy: 0.8447 - lr: 1.2500e-05
Epoch 3/5
186/186 [==============================] - 108s 580ms/step - loss: 0.1672 - accuracy: 0.9462 - val_loss: 0.5819 - val_accuracy: 0.8291 - lr: 1.2500e-05
Epoch 4/5
186/186 [==============================] - 108s 580ms/step - loss: 0.1595 - accuracy: 0.9499 - val_loss: 0.5063 - val_accuracy: 0.8555 - lr: 1.0000e-05
Epoch 5/5
186/186 [==============================] - 108s 580ms/step - loss: 0.1547 - accuracy: 0.9509 - val_loss: 0.4925 - val_accuracy: 0.8613 - lr: 1.0000e-05

In [ ]:
model.save('/content/gdrive/MyDrive/Colab Notebooks/Aidea/VGG_AIC_0515_0.9.h5')

#改至這 安裝圖片 先到pic改 再由這匯入

In [ ]:
a =["banana", "carrot", "corn" ,"dragonfruit", "garlic", "guava", "peanut", "pineapple", "pumpkin", "rice", "soybean", "sugarcane", "tomato", "bareland"]
test_df=pd.DataFrame()
for name in a:

  path = ('/content/gdrive/MyDrive/Colab Notebooks/Aidea/data/test_cut/'+name)
  df_path =os.listdir(path)
  plants=pd.DataFrame({'pic_name':df_path})
  plants['label']= name
  plants['path']= name+'/'+plants['pic_name']

  test_df=pd.concat([test_df,plants])
  # test_df=shuffle(all)
test_df

                 pic_name     label                           path
0        banana_test0.jpg    banana        banana/banana_test0.jpg
1        banana_test1.jpg    banana        banana/banana_test1.jpg
2        banana_test2.jpg    banana        banana/banana_test2.jpg
3        banana_test3.jpg    banana        banana/banana_test3.jpg
4        banana_test4.jpg    banana        banana/banana_test4.jpg
..                    ...       ...                            ...
195  bareland_test195.jpg  bareland  bareland/bareland_test195.jpg
196  bareland_test196.jpg  bareland  bareland/bareland_test196.jpg
197  bareland_test197.jpg  bareland  bareland/bareland_test197.jpg
198  bareland_test198.jpg  bareland  bareland/bareland_test198.jpg
199  bareland_test199.jpg  bareland  bareland/bareland_test199.jpg

[2800 rows x 3 columns]

In [ ]:
test_gen = ImageDataGenerator(rescale=1./255)
    
test_generator = test_gen.flow_from_dataframe(
    test_df,
    '/content/gdrive/MyDrive/Colab Notebooks/Aidea/data/test_cut/',
    x_col='path',
    y_col= None, #由程式給
    class_mode=None,
    target_size=image_size,
    batch_size=1,
    shuffle=False
)

Found 2800 validated image filenames.

In [ ]:
nb_sample =test_df.shape[0]
predict=model.predict(test_generator,steps=nb_sample)
print(len(predict))
print(predict)

2800
[[9.8076469e-01 1.3385169e-05 2.7302411e-05 ... 1.7112480e-07
  3.1270669e-03 3.0759506e-06]
 [9.9944741e-01 1.5332416e-05 7.1381955e-06 ... 7.4782429e-07
  1.9629460e-04 1.4823135e-05]
 [2.7077561e-02 4.2364892e-04 2.4265642e-03 ... 5.4090680e-03
  4.5713090e-04 5.7153322e-04]
 ...
 [5.2464598e-05 5.6840811e-02 1.2302393e-01 ... 2.6992275e-03
  2.1608392e-04 4.8420929e-06]
 [9.1866699e-05 9.9016553e-01 3.2180978e-04 ... 3.6904294e-06
  4.9202536e-05 1.6073901e-04]
 [1.3804707e-05 9.9693131e-01 2.2474378e-04 ... 9.3714494e-05
  4.2512388e-06 1.0405216e-05]]

In [ ]:
test_df['predict'] = np.argmax(predict,axis=-1).astype('int32')
test_df

                 pic_name     label                           path  predict
0        banana_test0.jpg    banana        banana/banana_test0.jpg        0
1        banana_test1.jpg    banana        banana/banana_test1.jpg        0
2        banana_test2.jpg    banana        banana/banana_test2.jpg        6
3        banana_test3.jpg    banana        banana/banana_test3.jpg        0
4        banana_test4.jpg    banana        banana/banana_test4.jpg        0
..                    ...       ...                            ...      ...
195  bareland_test195.jpg  bareland  bareland/bareland_test195.jpg        1
196  bareland_test196.jpg  bareland  bareland/bareland_test196.jpg        7
197  bareland_test197.jpg  bareland  bareland/bareland_test197.jpg        7
198  bareland_test198.jpg  bareland  bareland/bareland_test198.jpg        1
199  bareland_test199.jpg  bareland  bareland/bareland_test199.jpg        1

[2800 rows x 4 columns]

In [ ]:
labels=(train_generator.class_indices)
labels=dict((v,k) for k,v in labels.items())
labels

{0: 'banana',
 1: 'bareland',
 2: 'carrot',
 3: 'corn',
 4: 'dragonfruit',
 5: 'garlic',
 6: 'guava',
 7: 'peanut',
 8: 'pineapple',
 9: 'pumpkin',
 10: 'rice',
 11: 'soybean',
 12: 'sugarcane',
 13: 'tomato'}

In [ ]:
test_df['predict'] = test_df['predict'].map({0: 'banana',
 1: 'bareland',
 2: 'carrot',
 3: 'corn',
 4: 'dragonfruit',
 5: 'garlic',
 6: 'guava',
 7: 'peanut',
 8: 'pineapple',
 9: 'pumpkin',
 10: 'rice',
 11: 'soybean',
 12: 'sugarcane',
 13: 'tomato'})

In [ ]:
test_df

                 pic_name     label                           path   predict
0        banana_test0.jpg    banana        banana/banana_test0.jpg    banana
1        banana_test1.jpg    banana        banana/banana_test1.jpg    banana
2        banana_test2.jpg    banana        banana/banana_test2.jpg     guava
3        banana_test3.jpg    banana        banana/banana_test3.jpg    banana
4        banana_test4.jpg    banana        banana/banana_test4.jpg    banana
..                    ...       ...                            ...       ...
195  bareland_test195.jpg  bareland  bareland/bareland_test195.jpg  bareland
196  bareland_test196.jpg  bareland  bareland/bareland_test196.jpg    peanut
197  bareland_test197.jpg  bareland  bareland/bareland_test197.jpg    peanut
198  bareland_test198.jpg  bareland  bareland/bareland_test198.jpg  bareland
199  bareland_test199.jpg  bareland  bareland/bareland_test199.jpg  bareland

[2800 rows x 4 columns]

In [ ]:
test_df[test_df['label']!=test_df['predict']]

,pic_name,label,path,predict
2,banana_test2.jpg,banana,banana/banana_test2.jpg,guava
10,banana_test10.jpg,banana,banana/banana_test10.jpg,peanut
11,banana_test11.jpg,banana,banana/banana_test11.jpg,sugarcane
25,banana_test25.jpg,banana,banana/banana_test25.jpg,dragonfruit
28,banana_test28.jpg,banana,banana/banana_test28.jpg,corn
...,...,...,...,...
189,bareland_test189.jpg,bareland,bareland/bareland_test189.jpg,pumpkin
190,bareland_test190.jpg,bareland,bareland/bareland_test190.jpg,sugarcane
192,bareland_test192.jpg,bareland,bareland/bareland_test192.jpg,carrot
196,bareland_test196.jpg,bareland,bareland/bareland_test196.jpg,peanut
197,bareland_test197.jpg,bareland,bareland/bareland_test197.jpg,peanut

In [ ]:
y_test=test_df['label'].astype('str').values
pre_y=np.argmax(predict,axis=-1)

In [ ]:
confusion = confusion_matrix(test_df['label'].astype('str').values, test_df['predict'].astype('str').values) #Act Pred.
# confusion

df_cm=pd.DataFrame(confusion, columns=["banana", "carrot", "corn" ,"dragonfruit", "garlic", "guava", "peanut", "pineapple", "pumpkin", "rice", "soybean", "sugarcane", "tomato", "bareland"],
                   index=["banana", "carrot", "corn" ,"dragonfruit", "garlic", "guava", "peanut", "pineapple", "pumpkin", "rice", "soybean", "sugarcane", "tomato", "bareland"])
df_cm.index.name="Real"
df_cm.columns.name="Predict"
df_cm

Predict,banana,carrot,corn,dragonfruit,garlic,guava,peanut,pineapple,pumpkin,rice,soybean,sugarcane,tomato,bareland
Real,,,,,,,,,,,,,,
banana,156,0,1,9,7,0,7,2,0,3,0,0,15,0
carrot,0,180,2,1,1,0,1,2,1,1,6,0,1,4
corn,0,1,89,0,0,22,1,22,1,0,36,21,3,4
dragonfruit,0,0,0,160,3,3,0,0,1,5,0,2,21,5
garlic,8,0,0,1,177,0,2,0,1,0,0,0,5,6
guava,0,4,4,1,1,164,1,0,2,0,0,0,4,19
peanut,1,0,1,8,9,3,120,0,1,31,1,3,6,16
pineapple,0,2,31,0,1,1,4,47,0,18,66,30,0,0
pumpkin,0,2,0,0,5,22,0,1,145,0,2,0,15,8
rice,1,0,6,2,2,3,14,2,1,112,15,16,4,22
soybean,0,52,15,0,0,5,1,7,6,11,101,0,1,1
sugarcane,0,2,15,2,0,46,2,14,1,7,37,52,12,10
tomato,1,0,0,3,8,6,0,1,0,1,1,0,177,2
bareland,3,4,2,3,24,10,2,0,4,1,12,2,10,123

# 123

In [ ]:
path_t = ('/content/gdrive/MyDrive/Colab Notebooks/Aidea/data/C11')
df_path_t =os.listdir(path_t)
TEST=pd.DataFrame({'pic_name':df_path_t})
TEST['path']= TEST['pic_name']

TEST

              pic_name              path
0     b2a7940d9d87.jpg  b2a7940d9d87.jpg
1     b6c86ede7d3e.jpg  b6c86ede7d3e.jpg
2     bd86bfa33cff.jpg  bd86bfa33cff.jpg
3     b7894fdd97eb.jpg  b7894fdd97eb.jpg
4     bef56d61f82e.jpg  bef56d61f82e.jpg
...                ...               ...
6419  b766b9e40a4e.jpg  b766b9e40a4e.jpg
6420  b159e8f017c2.jpg  b159e8f017c2.jpg
6421  bba57c9ec8da.jpg  bba57c9ec8da.jpg
6422  bafa0ee5739b.jpg  bafa0ee5739b.jpg
6423  be0fb4cb5df3.jpg  be0fb4cb5df3.jpg

[6424 rows x 2 columns]

In [ ]:

TEST_gen1 = ImageDataGenerator(rescale=1./255)
    
TEST_generator1 = TEST_gen1.flow_from_dataframe( 
    TEST,
    '/content/gdrive/MyDrive/Colab Notebooks/Aidea/data/C11/',
    x_col='path',
    y_col= None, #由程式給
    class_mode=None,
    target_size=image_size,
    batch_size=1,
    shuffle=False
)

Found 6424 validated image filenames.

In [ ]:
TEST_sample =TEST.shape[0]
TEST_predict=model.predict(TEST_generator1,steps=TEST_sample)
print(len(TEST_predict))
print(TEST_predict)

6424
[[1.01084085e-02 4.00163094e-03 2.91700572e-01 ... 2.39494488e-01
  1.14624957e-02 6.22438192e-02]
 [1.62557559e-03 3.52717980e-05 1.32436162e-06 ... 1.16671934e-08
  1.21395142e-05 6.56867360e-06]
 [3.37835518e-05 8.40963548e-05 9.95763659e-01 ... 2.71230331e-03
  4.25448197e-05 1.80861264e-06]
 ...
 [5.52437778e-05 1.54276309e-03 2.39056215e-04 ... 3.28442839e-04
  4.85113442e-01 9.07509960e-03]
 [9.61436726e-08 1.53246981e-06 2.31586945e-08 ... 8.69412364e-09
  1.26158015e-03 1.40697995e-10]
 [1.71573437e-03 2.01732176e-03 4.39355522e-03 ... 1.11372238e-02
  3.77283053e-04 2.13033762e-02]]

In [ ]:
TEST['predict'] = np.argmax(TEST_predict,axis=-1).astype('int32')
TEST

              pic_name              path  predict
0     b2a7940d9d87.jpg  b2a7940d9d87.jpg        2
1     b6c86ede7d3e.jpg  b6c86ede7d3e.jpg        8
2     bd86bfa33cff.jpg  bd86bfa33cff.jpg        2
3     b7894fdd97eb.jpg  b7894fdd97eb.jpg       12
4     bef56d61f82e.jpg  bef56d61f82e.jpg        5
...                ...               ...      ...
6419  b766b9e40a4e.jpg  b766b9e40a4e.jpg       11
6420  b159e8f017c2.jpg  b159e8f017c2.jpg        6
6421  bba57c9ec8da.jpg  bba57c9ec8da.jpg       12
6422  bafa0ee5739b.jpg  bafa0ee5739b.jpg        3
6423  be0fb4cb5df3.jpg  be0fb4cb5df3.jpg        9

[6424 rows x 3 columns]

In [ ]:
TESTlabels=(train_generator.class_indices)
TESTlabels=dict((v,k) for k,v in TESTlabels.items())
TESTlabels

{0: 'banana',
 1: 'bareland',
 2: 'carrot',
 3: 'corn',
 4: 'dragonfruit',
 5: 'garlic',
 6: 'guava',
 7: 'peanut',
 8: 'pineapple',
 9: 'pumpkin',
 10: 'rice',
 11: 'soybean',
 12: 'sugarcane',
 13: 'tomato'}

In [ ]:
TEST['predict'] = TEST['predict'].map({0: 'banana',
 1: 'bareland',
 2: 'carrot',
 3: 'corn',
 4: 'dragonfruit',
 5: 'garlic',
 6: 'guava',
 7: 'peanut',
 8: 'pineapple',
 9: 'pumpkin',
 10: 'rice',
 11: 'soybean',
 12: 'sugarcane',
 13: 'tomato'} )

In [ ]:
TEST

              pic_name              path    predict
0     b2a7940d9d87.jpg  b2a7940d9d87.jpg     carrot
1     b6c86ede7d3e.jpg  b6c86ede7d3e.jpg  pineapple
2     bd86bfa33cff.jpg  bd86bfa33cff.jpg     carrot
3     b7894fdd97eb.jpg  b7894fdd97eb.jpg  sugarcane
4     bef56d61f82e.jpg  bef56d61f82e.jpg     garlic
...                ...               ...        ...
6419  b766b9e40a4e.jpg  b766b9e40a4e.jpg    soybean
6420  b159e8f017c2.jpg  b159e8f017c2.jpg      guava
6421  bba57c9ec8da.jpg  bba57c9ec8da.jpg  sugarcane
6422  bafa0ee5739b.jpg  bafa0ee5739b.jpg       corn
6423  be0fb4cb5df3.jpg  be0fb4cb5df3.jpg    pumpkin

[6424 rows x 3 columns]

In [ ]:
Submission=pd.DataFrame(TEST,columns=['pic_name','predict'])

Submission.rename(columns={'pic_name': 'image_filename', 'predict': 'label'}, inplace=True)
Submission
# Submission.to_csv("/content/gdrive/MyDrive/Colab Notebooks/Aidea/Submission_AF.csv" ,index=False)

#參考

In [ ]:
test_gen = ImageDataGenerator(rescale=1./255)
    
test_generator = test_gen.flow_from_dataframe(
    test_df,
    '/content/gdrive/MyDrive/Colab Notebooks/Aidea/data/train/',
    x_col='path',
    y_col=None, #由程式給
    class_mode=None,
    target_size=image_size,
    batch_size=1,
    shuffle=False
)

Found 1050 validated image filenames.

In [ ]:
nb_sample =test_df.shape[0]
predict=model.predict(test_generator,steps=nb_sample)

In [ ]:
print(len(predict))
print(predict)

1050
[[3.6463100e-01 4.3539680e-03 4.1988301e-03 ... 7.4957107e-04
  5.2234838e-03 1.0020703e-02]
 [1.2859133e-05 4.2596488e-07 2.6749322e-04 ... 9.8483187e-01
  1.5381392e-08 3.4258644e-06]
 [3.2209430e-02 4.8068443e-05 3.8692115e-06 ... 3.8522694e-04
  2.0896861e-05 3.1706661e-02]
 ...
 [5.7670806e-02 7.9440214e-02 5.3462702e-01 ... 7.8715682e-02
  4.9754206e-02 2.3098852e-02]
 [5.7036933e-03 1.3633791e-06 6.1627934e-06 ... 7.5558119e-04
  1.6367236e-05 2.3631075e-05]
 [1.5257959e-03 2.6749939e-02 5.8810923e-02 ... 1.1532959e-03
  2.0583959e-03 2.9996971e-02]]

In [ ]:
test_df['predict'] = np.argmax(predict,axis=-1).astype('str')
test_df

                   pic_name label                                path predict
1           banana_cut1.jpg     0              banana/banana_cut1.jpg       9
20      pineapple_cut20.jpg     3       pineapple/pineapple_cut20.jpg      11
326  dragonfruit_cut326.jpg    11  dragonfruit/dragonfruit_cut326.jpg       7
250       tomato_cut250.jpg     8            tomato/tomato_cut250.jpg       4
307  dragonfruit_cut307.jpg    11  dragonfruit/dragonfruit_cut307.jpg       7
..                      ...   ...                                 ...     ...
39      sugarcane_cut39.jpg     7       sugarcane/sugarcane_cut39.jpg       3
259     bareland_cut259.jpg     9        bareland/bareland_cut259.jpg       5
494      pumpkin_cut494.jpg     4          pumpkin/pumpkin_cut494.jpg       2
382  dragonfruit_cut382.jpg    11  dragonfruit/dragonfruit_cut382.jpg       7
279      soybean_cut279.jpg     6          soybean/soybean_cut279.jpg      10

[1050 rows x 4 columns]

In [ ]:
test_df[test_df['label']!=test_df['predict']]

                   pic_name label                                path predict
1           banana_cut1.jpg     0              banana/banana_cut1.jpg       9
20      pineapple_cut20.jpg     3       pineapple/pineapple_cut20.jpg      11
326  dragonfruit_cut326.jpg    11  dragonfruit/dragonfruit_cut326.jpg       7
250       tomato_cut250.jpg     8            tomato/tomato_cut250.jpg       4
307  dragonfruit_cut307.jpg    11  dragonfruit/dragonfruit_cut307.jpg       7
..                      ...   ...                                 ...     ...
39      sugarcane_cut39.jpg     7       sugarcane/sugarcane_cut39.jpg       3
259     bareland_cut259.jpg     9        bareland/bareland_cut259.jpg       5
494      pumpkin_cut494.jpg     4          pumpkin/pumpkin_cut494.jpg       2
382  dragonfruit_cut382.jpg    11  dragonfruit/dragonfruit_cut382.jpg       7
279      soybean_cut279.jpg     6          soybean/soybean_cut279.jpg      10

[926 rows x 4 columns]

In [ ]:
y_test=test_df['label'].astype('int32').values
pre_y=np.argmax(predict,axis=-1)

In [ ]:
confusion = confusion_matrix(test_df['label'].astype('int32').values, np.argmax(predict, axis=-1)) #Act Pred.
confusion

array([[69,  0,  2,  3,  2,  0,  2,  3,  0,  6,  1,  1,  1,  0],
       [ 0, 52, 11,  0,  2,  0,  0,  0, 10,  0, 13,  0,  0,  0],
       [ 0,  3,  9,  1,  0,  4,  0,  0,  4,  0, 43,  0,  0,  2],
       [ 0,  0,  2,  1,  1,  1,  1,  1,  3,  0,  0, 61,  0,  5],
       [ 0,  1, 13,  0,  2,  0,  0,  1,  5,  7,  1,  3, 30,  1],
       [ 0,  0,  5,  0,  1,  1,  0,  0,  3,  0,  0,  3,  1, 57],
       [ 0,  2, 40,  2,  1,  0,  0,  0,  5,  0, 13,  0,  3,  2],
       [ 0,  0,  1, 46,  1,  0,  0,  0,  9,  3,  0,  2,  0,  3],
       [ 0,  1,  4,  4, 44,  0,  0,  3, 15,  1,  1,  1,  1,  3],
       [ 0,  0,  1,  1,  1, 66,  0,  0,  0,  0,  1,  1,  0,  0],
       [ 0,  0,  1,  1,  1,  0, 52,  1, 17,  1,  0,  1,  1,  0],
       [ 0,  0,  0,  0,  4,  0,  3, 68,  3, 10,  1,  2,  1,  1],
       [ 0,  0,  2,  0,  0,  0,  0,  0, 67,  0,  0,  0,  0,  0],
       [ 0,  0,  2,  1,  4,  0,  5,  6,  8, 48,  0,  0,  1,  0]])

In [ ]:
df_cm=pd.DataFrame(confusion, columns=["banana", "carrot", "corn" ,"dragonfruit", "garlic", "guava", "peanut", "pineapple", "pumpkin", "rice", "soybean", "sugarcane", "tomato", "bareland"],
                   index=["banana", "carrot", "corn" ,"dragonfruit", "garlic", "guava", "peanut", "pineapple", "pumpkin", "rice", "soybean", "sugarcane", "tomato", "bareland"])
df_cm.index.name="Real"
df_cm.columns.name="Predict"
df_cm

Predict,banana,carrot,corn,dragonfruit,garlic,guava,peanut,pineapple,pumpkin,rice,soybean,sugarcane,tomato,bareland
Real,,,,,,,,,,,,,,
banana,69,0,2,3,2,0,2,3,0,6,1,1,1,0
carrot,0,52,11,0,2,0,0,0,10,0,13,0,0,0
corn,0,3,9,1,0,4,0,0,4,0,43,0,0,2
dragonfruit,0,0,2,1,1,1,1,1,3,0,0,61,0,5
garlic,0,1,13,0,2,0,0,1,5,7,1,3,30,1
guava,0,0,5,0,1,1,0,0,3,0,0,3,1,57
peanut,0,2,40,2,1,0,0,0,5,0,13,0,3,2
pineapple,0,0,1,46,1,0,0,0,9,3,0,2,0,3
pumpkin,0,1,4,4,44,0,0,3,15,1,1,1,1,3
rice,0,0,1,1,1,66,0,0,0,0,1,1,0,0
soybean,0,0,1,1,1,0,52,1,17,1,0,1,1,0
sugarcane,0,0,0,0,4,0,3,68,3,10,1,2,1,1
tomato,0,0,2,0,0,0,0,0,67,0,0,0,0,0
bareland,0,0,2,1,4,0,5,6,8,48,0,0,1,0

In [ ]:
labels=(train_generator.class_indices)
labels

labels=dict((v,k) for k,v in labels.items())
# predictions = [labels[k] for k in predicted_class]

# predictions

In [ ]:
labels

{0: '0',
 1: '1',
 2: '10',
 3: '11',
 4: '12',
 5: '13',
 6: '2',
 7: '3',
 8: '4',
 9: '5',
 10: '6',
 11: '7',
 12: '8',
 13: '9'}

In [ ]:
test_df

                   pic_name label                                path predict
1           banana_cut1.jpg     0              banana/banana_cut1.jpg       9
20      pineapple_cut20.jpg     3       pineapple/pineapple_cut20.jpg      11
326  dragonfruit_cut326.jpg    11  dragonfruit/dragonfruit_cut326.jpg       7
250       tomato_cut250.jpg     8            tomato/tomato_cut250.jpg       4
307  dragonfruit_cut307.jpg    11  dragonfruit/dragonfruit_cut307.jpg       7
..                      ...   ...                                 ...     ...
39      sugarcane_cut39.jpg     7       sugarcane/sugarcane_cut39.jpg       3
259     bareland_cut259.jpg     9        bareland/bareland_cut259.jpg       5
494      pumpkin_cut494.jpg     4          pumpkin/pumpkin_cut494.jpg       2
382  dragonfruit_cut382.jpg    11  dragonfruit/dragonfruit_cut382.jpg       7
279      soybean_cut279.jpg     6          soybean/soybean_cut279.jpg      10

[1050 rows x 4 columns]

In [ ]:
test_df[test_df['label']!=test_df['predict']]

                 pic_name label                            path predict
254    pumpkin_cut254.jpg     8      pumpkin/pumpkin_cut254.jpg      12
383  sugarcane_cut383.jpg    11  sugarcane/sugarcane_cut383.jpg       8
479  sugarcane_cut479.jpg    11  sugarcane/sugarcane_cut479.jpg       3
243       corn_cut243.jpg     2            corn/corn_cut243.jpg       6
115     tomato_cut115.jpg    12        tomato/tomato_cut115.jpg       4
..                    ...   ...                             ...     ...
49      soybean_cut49.jpg    10       soybean/soybean_cut49.jpg      13
189   bareland_cut189.jpg    13    bareland/bareland_cut189.jpg       5
326    soybean_cut326.jpg    10      soybean/soybean_cut326.jpg       2
257      guava_cut257.jpg     5          guava/guava_cut257.jpg       7
442     peanut_cut442.jpg     6        peanut/peanut_cut442.jpg      10

[918 rows x 4 columns]

In [ ]:
test_df['predict'] = test_df['predict'].map({'0': '0',
 '1': '1',
 '2': '10',
 '3': '11',
 '4': '12',
 '5': '13',
 '6': '2',
 '7': '3',
 '8': '4',
 '9': '5',
 '10': '6',
 '11': '7',
 '12': '8',
 '13': '9'}                           )